version: '3'

services: 

  app:
    image: evincarsn/node-nginx-fullcycle:latest
    container_name: app
    restart: always   
    networks: 
      - node-network
    tty: true   
    depends_on: 
      - db

  db:
    build: 
      context: .
      dockerfile: Dockerfile.prod   
    command: --innodb-use-native-aio=0
    container_name: db    
    tty: true
    volumes:      
      - ./mysql:/var/lib/mysql          
    environment: 
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks: 
      - node-network   

  nginx:
    build: 
      context: ./nginx
      dockerfile: Dockerfile.prod    
    container_name: nginx
    restart: always
    ports:
      - "8080:80" 
    networks: 
      - node-network     

networks: 
  node-network:
    driver: bridge 