version: '3'

services: 

  app:
    build: 
      context: ./node
      dockerfile: Dockerfile.prod 
    container_name: app
    entrypoint: dockerize -wait tcp://db:3306 -timeout 30s sh -c "npm install && node index.js"
    networks: 
      - node-network
    volumes: 
      - ./node:/usr/src/app
    tty: true   
    depends_on: 
      - db

  db:
    build: 
      context: .
      dockerfile: Dockerfile.prod   
    command: --innodb-use-native-aio=0
    container_name: db      
    tty: true
    volumes:      
      - ./mysql:/var/lib/mysql          
    environment: 
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks: 
      - node-network   

  nginx:
    build: 
      context: ./nginx
      dockerfile: Dockerfile.prod    
    container_name: nginx
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80" 
    networks: 
      - node-network 
    depends_on:
      - app      

networks: 
  node-network:
    driver: bridge 